//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApparatus.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectApparatus.Lang.zh_CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 物体 的本地化字符串。
        /// </summary>
        internal static string _object {
            get {
                return ResourceManager.GetString("object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改跳跃高度 的本地化字符串。
        /// </summary>
        internal static string adjust_jump_height {
            get {
                return ResourceManager.GetString("adjust_jump_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许修改跳跃高度。 的本地化字符串。
        /// </summary>
        internal static string adjust_jump_height_descr {
            get {
                return ResourceManager.GetString("adjust_jump_height_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改奔跑速度 的本地化字符串。
        /// </summary>
        internal static string adjust_sprint_speed {
            get {
                return ResourceManager.GetString("adjust_sprint_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许修改奔跑速度。 的本地化字符串。
        /// </summary>
        internal static string adjust_sprint_speed_descr {
            get {
                return ResourceManager.GetString("adjust_sprint_speed_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改行走速度 的本地化字符串。
        /// </summary>
        internal static string adjust_walk_speed {
            get {
                return ResourceManager.GetString("adjust_walk_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许修改行走速度。 的本地化字符串。
        /// </summary>
        internal static string adjust_walk_speed_descr {
            get {
                return ResourceManager.GetString("adjust_walk_speed_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸引怪物注意 的本地化字符串。
        /// </summary>
        internal static string aggro_enemies {
            get {
                return ResourceManager.GetString("aggro_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强迫怪物攻击指定的玩家。 的本地化字符串。
        /// </summary>
        internal static string aggro_enemies_descr_1 {
            get {
                return ResourceManager.GetString("aggro_enemies_descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对大多数怪物无效，在半身鱼和蜘蛛上效果最佳。 的本地化字符串。
        /// </summary>
        internal static string aggro_enemies_descr_2 {
            get {
                return ResourceManager.GetString("aggro_enemies_descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有喷气背包爆炸 的本地化字符串。
        /// </summary>
        internal static string all_jetpacks_explode {
            get {
                return ResourceManager.GetString("all_jetpacks_explode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当有玩家尝试装备喷气背包时，将受到轰轰烈烈的欢迎。 的本地化字符串。
        /// </summary>
        internal static string all_jetpacks_explode_descr {
            get {
                return ResourceManager.GetString("all_jetpacks_explode_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总是显示时间 的本地化字符串。
        /// </summary>
        internal static string always_show_clock {
            get {
                return ResourceManager.GetString("always_show_clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 即使在设施内，也会显示时钟。 的本地化字符串。
        /// </summary>
        internal static string always_show_clock_descr {
            get {
                return ResourceManager.GetString("always_show_clock_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 攻击出售台的玩家 的本地化字符串。
        /// </summary>
        internal static string attack_players_at_deposit_desk {
            get {
                return ResourceManager.GetString("attack_players_at_deposit_desk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强迫触手怪物（老板）发动攻击，击毙附近的玩家。 的本地化字符串。
        /// </summary>
        internal static string attack_players_at_deposit_desk_descr {
            get {
                return ResourceManager.GetString("attack_players_at_deposit_desk_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大型战利品 的本地化字符串。
        /// </summary>
        internal static string big_loot {
            get {
                return ResourceManager.GetString("big_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制游戏以完整分辨率渲染。 的本地化字符串。
        /// </summary>
        internal static string camera_res_descr_1 {
            get {
                return ResourceManager.GetString("camera_res_descr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=#ff0000&gt;你需要离开游戏以使此功能生效。&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string camera_res_descr_2 {
            get {
                return ResourceManager.GetString("camera_res_descr_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指示器居中 的本地化字符串。
        /// </summary>
        internal static string centered_indicators {
            get {
                return ResourceManager.GetString("centered_indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在屏幕中央显示指示器。 的本地化字符串。
        /// </summary>
        internal static string centered_indicators_descr {
            get {
                return ResourceManager.GetString("centered_indicators_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新日志 的本地化字符串。
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给任何物品充电 的本地化字符串。
        /// </summary>
        internal static string charge_any_item {
            get {
                return ResourceManager.GetString("charge_any_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你将任何可抓取的物品放入充电器。 的本地化字符串。
        /// </summary>
        internal static string charge_any_item_descr {
            get {
                return ResourceManager.GetString("charge_any_item_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭所有气密门 的本地化字符串。
        /// </summary>
        internal static string close_all_mechanical_doors {
            get {
                return ResourceManager.GetString("close_all_mechanical_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭所有气密门。 的本地化字符串。
        /// </summary>
        internal static string close_all_mechanical_doors_descr {
            get {
                return ResourceManager.GetString("close_all_mechanical_doors_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        internal static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者 的本地化字符串。
        /// </summary>
        internal static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准星 的本地化字符串。
        /// </summary>
        internal static string crosshair {
            get {
                return ResourceManager.GetString("crosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在屏幕上显示一个准星。 的本地化字符串。
        /// </summary>
        internal static string crosshair_descr {
            get {
                return ResourceManager.GetString("crosshair_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 攻击 的本地化字符串。
        /// </summary>
        internal static string damage {
            get {
                return ResourceManager.GetString("damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对玩家造成一定数额的伤害。 的本地化字符串。
        /// </summary>
        internal static string damage_descr {
            get {
                return ResourceManager.GetString("damage_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余天数 的本地化字符串。
        /// </summary>
        internal static string days_left {
            get {
                return ResourceManager.GetString("days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 死亡玩家列表 的本地化字符串。
        /// </summary>
        internal static string dead_players {
            get {
                return ResourceManager.GetString("dead_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示一个已死亡玩家的列表。 的本地化字符串。
        /// </summary>
        internal static string dead_players_descr {
            get {
                return ResourceManager.GetString("dead_players_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除物品 的本地化字符串。
        /// </summary>
        internal static string del_object {
            get {
                return ResourceManager.GetString("del_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除你拿着的物品。 的本地化字符串。
        /// </summary>
        internal static string del_object_desc {
            get {
                return ResourceManager.GetString("del_object_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除全部敌人 的本地化字符串。
        /// </summary>
        internal static string delete_all_enemies {
            get {
                return ResourceManager.GetString("delete_all_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除全部敌人。 的本地化字符串。
        /// </summary>
        internal static string delete_all_enemies_descr {
            get {
                return ResourceManager.GetString("delete_all_enemies_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半神 的本地化字符串。
        /// </summary>
        internal static string demigod {
            get {
                return ResourceManager.GetString("demigod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果选中的玩家生命值低于零，自动为其补满健康。 的本地化字符串。
        /// </summary>
        internal static string demigod_descr {
            get {
                return ResourceManager.GetString("demigod_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用景深 的本地化字符串。
        /// </summary>
        internal static string disable_dof {
            get {
                return ResourceManager.GetString("disable_dof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用景深效果。 的本地化字符串。
        /// </summary>
        internal static string disable_dof_descr {
            get {
                return ResourceManager.GetString("disable_dof_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用跌落伤害 的本地化字符串。
        /// </summary>
        internal static string disable_fall_damage {
            get {
                return ResourceManager.GetString("disable_fall_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使你不再受到跌落伤害。 的本地化字符串。
        /// </summary>
        internal static string disable_fall_damage_descr {
            get {
                return ResourceManager.GetString("disable_fall_damage_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用雾 的本地化字符串。
        /// </summary>
        internal static string disable_fog {
            get {
                return ResourceManager.GetString("disable_fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用雾效果。 的本地化字符串。
        /// </summary>
        internal static string disable_fog_descr {
            get {
                return ResourceManager.GetString("disable_fog_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用互动冷却 的本地化字符串。
        /// </summary>
        internal static string disable_interact_cooldowns {
            get {
                return ResourceManager.GetString("disable_interact_cooldowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用所有互动的冷却时间（例如，大喇叭、厕所等）。 的本地化字符串。
        /// </summary>
        internal static string disable_interact_cooldowns_descr {
            get {
                return ResourceManager.GetString("disable_interact_cooldowns_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用面罩 的本地化字符串。
        /// </summary>
        internal static string disable_visor {
            get {
                return ResourceManager.GetString("disable_visor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用第一人称视角中头盔上的面罩。 的本地化字符串。
        /// </summary>
        internal static string disable_visor_descr {
            get {
                return ResourceManager.GetString("disable_visor_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示剩余天数 的本地化字符串。
        /// </summary>
        internal static string display_days_left {
            get {
                return ResourceManager.GetString("display_days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示你需要满足指标的剩余天数。 的本地化字符串。
        /// </summary>
        internal static string display_days_left_descr {
            get {
                return ResourceManager.GetString("display_days_left_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示距离 的本地化字符串。
        /// </summary>
        internal static string display_distance {
            get {
                return ResourceManager.GetString("display_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示你与实体之间的距离。 的本地化字符串。
        /// </summary>
        internal static string display_distance_esp_descr {
            get {
                return ResourceManager.GetString("display_distance_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示团队金钱 的本地化字符串。
        /// </summary>
        internal static string display_group_credits {
            get {
                return ResourceManager.GetString("display_group_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示你拥有的金钱的数量。 的本地化字符串。
        /// </summary>
        internal static string display_group_credits_descr {
            get {
                return ResourceManager.GetString("display_group_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示生命值 的本地化字符串。
        /// </summary>
        internal static string display_hp {
            get {
                return ResourceManager.GetString("display_hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示玩家的生命值。 的本地化字符串。
        /// </summary>
        internal static string display_hp_esp_descr {
            get {
                return ResourceManager.GetString("display_hp_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示飞船里的物品 的本地化字符串。
        /// </summary>
        internal static string display_loot_in_ship {
            get {
                return ResourceManager.GetString("display_loot_in_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示您在飞船上收集的所有物品的价值。 的本地化字符串。
        /// </summary>
        internal static string display_loot_in_ship_descr {
            get {
                return ResourceManager.GetString("display_loot_in_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示指标 的本地化字符串。
        /// </summary>
        internal static string display_quota {
            get {
                return ResourceManager.GetString("display_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前指标。 的本地化字符串。
        /// </summary>
        internal static string display_quota_descr {
            get {
                return ResourceManager.GetString("display_quota_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示正在说话的人 的本地化字符串。
        /// </summary>
        internal static string display_speaking {
            get {
                return ResourceManager.GetString("display_speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示玩家是否在说话。 的本地化字符串。
        /// </summary>
        internal static string display_speaking_esp_descr {
            get {
                return ResourceManager.GetString("display_speaking_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示价值 的本地化字符串。
        /// </summary>
        internal static string display_worth {
            get {
                return ResourceManager.GetString("display_worth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示物品的价值。 的本地化字符串。
        /// </summary>
        internal static string display_worth_esp_descr {
            get {
                return ResourceManager.GetString("display_worth_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离 的本地化字符串。
        /// </summary>
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门 的本地化字符串。
        /// </summary>
        internal static string door {
            get {
                return ResourceManager.GetString("door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门 的本地化字符串。
        /// </summary>
        internal static string door_esp {
            get {
                return ResourceManager.GetString("door_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有门。 的本地化字符串。
        /// </summary>
        internal static string door_esp_descr {
            get {
                return ResourceManager.GetString("door_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总开关 的本地化字符串。
        /// </summary>
        internal static string enable_esp {
            get {
                return ResourceManager.GetString("enable_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启绘制功能。 的本地化字符串。
        /// </summary>
        internal static string enable_esp_descr {
            get {
                return ResourceManager.GetString("enable_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物 的本地化字符串。
        /// </summary>
        internal static string enemy {
            get {
                return ResourceManager.GetString("enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物绘制距离限制 的本地化字符串。
        /// </summary>
        internal static string enemy_distance_limit {
            get {
                return ResourceManager.GetString("enemy_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开关以设置怪物绘制距离限制。 的本地化字符串。
        /// </summary>
        internal static string enemy_distance_limit_descr {
            get {
                return ResourceManager.GetString("enemy_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物 的本地化字符串。
        /// </summary>
        internal static string enemy_esp {
            get {
                return ResourceManager.GetString("enemy_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有怪物。 的本地化字符串。
        /// </summary>
        internal static string enemy_esp_descr {
            get {
                return ResourceManager.GetString("enemy_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入口 的本地化字符串。
        /// </summary>
        internal static string entrance {
            get {
                return ResourceManager.GetString("entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绘制 的本地化字符串。
        /// </summary>
        internal static string esp {
            get {
                return ResourceManager.GetString("esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引爆所有地雷 的本地化字符串。
        /// </summary>
        internal static string explode_all_mines {
            get {
                return ResourceManager.GetString("explode_all_mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引爆关卡里的所有地雷。 的本地化字符串。
        /// </summary>
        internal static string explode_all_mines_descr {
            get {
                return ResourceManager.GetString("explode_all_mines_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速爬梯子 的本地化字符串。
        /// </summary>
        internal static string fast_ladder_climbing {
            get {
                return ResourceManager.GetString("fast_ladder_climbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即爬上梯子。 的本地化字符串。
        /// </summary>
        internal static string fast_ladder_climbing_descr {
            get {
                return ResourceManager.GetString("fast_ladder_climbing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视野 的本地化字符串。
        /// </summary>
        internal static string fov {
            get {
                return ResourceManager.GetString("fov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给予金钱 的本地化字符串。
        /// </summary>
        internal static string give_credits {
            get {
                return ResourceManager.GetString("give_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给予你的团队任意数量的金钱（不适用于指标）。 的本地化字符串。
        /// </summary>
        internal static string give_credits_descr {
            get {
                return ResourceManager.GetString("give_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无敌模式 的本地化字符串。
        /// </summary>
        internal static string god_mode {
            get {
                return ResourceManager.GetString("god_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防止你受到任何伤害。 的本地化字符串。
        /// </summary>
        internal static string god_mode_descr {
            get {
                return ResourceManager.GetString("god_mode_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像 的本地化字符串。
        /// </summary>
        internal static string graphics {
            get {
                return ResourceManager.GetString("graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 团队金钱 的本地化字符串。
        /// </summary>
        internal static string group_credits {
            get {
                return ResourceManager.GetString("group_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 治疗 的本地化字符串。
        /// </summary>
        internal static string heal {
            get {
                return ResourceManager.GetString("heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 治疗玩家一定数量的生命值。 的本地化字符串。
        /// </summary>
        internal static string heal_descr {
            get {
                return ResourceManager.GetString("heal_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺风耳 的本地化字符串。
        /// </summary>
        internal static string hear_everyone {
            get {
                return ResourceManager.GetString("hear_everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你听到所有人的声音，无论距离多远。 的本地化字符串。
        /// </summary>
        internal static string hear_everyone_descr {
            get {
                return ResourceManager.GetString("hear_everyone_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置手持物品价值 的本地化字符串。
        /// </summary>
        internal static string held_item_val {
            get {
                return ResourceManager.GetString("held_item_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将你手持物品的价值设置为你在上面选择的值。 的本地化字符串。
        /// </summary>
        internal static string held_item_val_desc {
            get {
                return ResourceManager.GetString("held_item_val_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好 世界！ 的本地化字符串。
        /// </summary>
        internal static string hello_world {
            get {
                return ResourceManager.GetString("hello_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏物品 的本地化字符串。
        /// </summary>
        internal static string hide_objects {
            get {
                return ResourceManager.GetString("hide_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏来自选定玩家的刷屏物品。 的本地化字符串。
        /// </summary>
        internal static string hide_objects_descr {
            get {
                return ResourceManager.GetString("hide_objects_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限电量 的本地化字符串。
        /// </summary>
        internal static string infinite_charge {
            get {
                return ResourceManager.GetString("infinite_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防止你的物品电量减少。 的本地化字符串。
        /// </summary>
        internal static string infinite_charge_descr {
            get {
                return ResourceManager.GetString("infinite_charge_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限使用 的本地化字符串。
        /// </summary>
        internal static string infinite_items {
            get {
                return ResourceManager.GetString("infinite_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你无限使用礼盒和闪光手雷等物品。（存在问题） 的本地化字符串。
        /// </summary>
        internal static string infinite_items_descr {
            get {
                return ResourceManager.GetString("infinite_items_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限子弹 的本地化字符串。
        /// </summary>
        internal static string infinite_shotgun_ammo {
            get {
                return ResourceManager.GetString("infinite_shotgun_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防止你耗尽弹药 的本地化字符串。
        /// </summary>
        internal static string infinite_shotgun_ammo_descr {
            get {
                return ResourceManager.GetString("infinite_shotgun_ammo_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限体力 的本地化字符串。
        /// </summary>
        internal static string infinite_stam {
            get {
                return ResourceManager.GetString("infinite_stam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防止你失去体力 的本地化字符串。
        /// </summary>
        internal static string infinite_stam_descr {
            get {
                return ResourceManager.GetString("infinite_stam_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限电击枪 的本地化字符串。
        /// </summary>
        internal static string infinite_zap_gun {
            get {
                return ResourceManager.GetString("infinite_zap_gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用电击枪时无限制地使敌人晕眩。 的本地化字符串。
        /// </summary>
        internal static string infinite_zap_gun_descr {
            get {
                return ResourceManager.GetString("infinite_zap_gun_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 即时互动 的本地化字符串。
        /// </summary>
        internal static string instant_interactions {
            get {
                return ResourceManager.GetString("instant_interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使所有按住操作瞬间完成。（例如开门） 的本地化字符串。
        /// </summary>
        internal static string instant_interactions_descr {
            get {
                return ResourceManager.GetString("instant_interactions_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 穿墙互动 的本地化字符串。
        /// </summary>
        internal static string interact_through_walls {
            get {
                return ResourceManager.GetString("interact_through_walls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许您透过墙壁与任何物体互动。 的本地化字符串。
        /// </summary>
        internal static string interact_through_walls_descr {
            get {
                return ResourceManager.GetString("interact_through_walls_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐身 的本地化字符串。
        /// </summary>
        internal static string invisibility {
            get {
                return ResourceManager.GetString("invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家们将看不见你。 的本地化字符串。
        /// </summary>
        internal static string invisibility_desc {
            get {
                return ResourceManager.GetString("invisibility_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品绘制距离限制 的本地化字符串。
        /// </summary>
        internal static string item_distance_limit {
            get {
                return ResourceManager.GetString("item_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开关以设置物品绘制距离限制。 的本地化字符串。
        /// </summary>
        internal static string item_distance_limit_descr {
            get {
                return ResourceManager.GetString("item_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品 的本地化字符串。
        /// </summary>
        internal static string item_esp {
            get {
                return ResourceManager.GetString("item_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有物品。 的本地化字符串。
        /// </summary>
        internal static string item_esp_descr {
            get {
                return ResourceManager.GetString("item_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死 的本地化字符串。
        /// </summary>
        internal static string kill {
            get {
                return ResourceManager.GetString("kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死所有怪物 的本地化字符串。
        /// </summary>
        internal static string kill_all_enemies {
            get {
                return ResourceManager.GetString("kill_all_enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死所有怪物。 的本地化字符串。
        /// </summary>
        internal static string kill_all_enemies_descr {
            get {
                return ResourceManager.GetString("kill_all_enemies_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死选中的玩家。 的本地化字符串。
        /// </summary>
        internal static string kill_descr {
            get {
                return ResourceManager.GetString("kill_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降落飞船 的本地化字符串。
        /// </summary>
        internal static string land_ship {
            get {
                return ResourceManager.GetString("land_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降落飞船。 的本地化字符串。
        /// </summary>
        internal static string land_ship_descr {
            get {
                return ResourceManager.GetString("land_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地雷 的本地化字符串。
        /// </summary>
        internal static string landmine {
            get {
                return ResourceManager.GetString("landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开关以设置地雷的绘制距离限制。 的本地化字符串。
        /// </summary>
        internal static string landmine_distance_limit_descr {
            get {
                return ResourceManager.GetString("landmine_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地雷 的本地化字符串。
        /// </summary>
        internal static string landmine_esp {
            get {
                return ResourceManager.GetString("landmine_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有地雷。 的本地化字符串。
        /// </summary>
        internal static string landmine_esp_descr {
            get {
                return ResourceManager.GetString("landmine_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灯光秀 的本地化字符串。
        /// </summary>
        internal static string light_show {
            get {
                return ResourceManager.GetString("light_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速开关飞船上的灯和电视。 的本地化字符串。
        /// </summary>
        internal static string light_show_descr {
            get {
                return ResourceManager.GetString("light_show_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战利品 的本地化字符串。
        /// </summary>
        internal static string loot {
            get {
                return ResourceManager.GetString("loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船上的战利品 的本地化字符串。
        /// </summary>
        internal static string loot_in_ship {
            get {
                return ResourceManager.GetString("loot_in_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中型战利品 的本地化字符串。
        /// </summary>
        internal static string medium_loot {
            get {
                return ResourceManager.GetString("medium_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地雷绘制距离限制 的本地化字符串。
        /// </summary>
        internal static string mine_distance_limit {
            get {
                return ResourceManager.GetString("mine_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杂项 的本地化字符串。
        /// </summary>
        internal static string misc {
            get {
                return ResourceManager.GetString("misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜视 的本地化字符串。
        /// </summary>
        internal static string night_vision {
            get {
                return ResourceManager.GetString("night_vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使你在黑暗中也能看得见。 的本地化字符串。
        /// </summary>
        internal static string night_vision_descr {
            get {
                return ResourceManager.GetString("night_vision_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未持有物体 的本地化字符串。
        /// </summary>
        internal static string no_held_object {
            get {
                return ResourceManager.GetString("no_held_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不再有更多金钱 的本地化字符串。
        /// </summary>
        internal static string no_more_credits {
            get {
                return ResourceManager.GetString("no_more_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阻止你的团队获得任何金钱。（不适用于指标） 的本地化字符串。
        /// </summary>
        internal static string no_more_credits_descr {
            get {
                return ResourceManager.GetString("no_more_credits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行模式 的本地化字符串。
        /// </summary>
        internal static string noclip {
            get {
                return ResourceManager.GetString("noclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你飞行和穿墙。 的本地化字符串。
        /// </summary>
        internal static string noclip_descr {
            get {
                return ResourceManager.GetString("noclip_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要生成的物体 的本地化字符串。
        /// </summary>
        internal static string obj_to_spawn {
            get {
                return ResourceManager.GetString("obj_to_spawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物体轰炸 的本地化字符串。
        /// </summary>
        internal static string object_spam {
            get {
                return ResourceManager.GetString("object_spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反复在玩家身上放置物体，以捉弄他们。 的本地化字符串。
        /// </summary>
        internal static string object_spam_descr {
            get {
                return ResourceManager.GetString("object_spam_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 腕豪 的本地化字符串。
        /// </summary>
        internal static string one_hand_all_objects {
            get {
                return ResourceManager.GetString("one_hand_all_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你单手拿起任何双手物品。 的本地化字符串。
        /// </summary>
        internal static string one_hand_all_objects_descr {
            get {
                return ResourceManager.GetString("one_hand_all_objects_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启所有气密门 的本地化字符串。
        /// </summary>
        internal static string open_all_mechanical_doors {
            get {
                return ResourceManager.GetString("open_all_mechanical_doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启所有气密门。 的本地化字符串。
        /// </summary>
        internal static string open_all_mechanical_doors_descr {
            get {
                return ResourceManager.GetString("open_all_mechanical_doors_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任意放置 的本地化字符串。
        /// </summary>
        internal static string place_anywhere {
            get {
                return ResourceManager.GetString("place_anywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在任意位置放置飞船上的物体。 的本地化字符串。
        /// </summary>
        internal static string place_anywhere_descr {
            get {
                return ResourceManager.GetString("place_anywhere_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        internal static string player_esp {
            get {
                return ResourceManager.GetString("player_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        internal static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有玩家。 的本地化字符串。
        /// </summary>
        internal static string players_esp_descr {
            get {
                return ResourceManager.GetString("players_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制最近的怪物 的本地化字符串。
        /// </summary>
        internal static string possess_nearest_enemy {
            get {
                return ResourceManager.GetString("possess_nearest_enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制最近的怪物。（注意：你将变成怪物视角。） 的本地化字符串。
        /// </summary>
        internal static string possess_nearest_enemy_descr {
            get {
                return ResourceManager.GetString("possess_nearest_enemy_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 利润指标 的本地化字符串。
        /// </summary>
        internal static string profit_quota {
            get {
                return ResourceManager.GetString("profit_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无重量 的本地化字符串。
        /// </summary>
        internal static string remove_weight {
            get {
                return ResourceManager.GetString("remove_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除由物品重量引起的速度限制。 的本地化字符串。
        /// </summary>
        internal static string remove_weight_descr {
            get {
                return ResourceManager.GetString("remove_weight_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最高分辨率渲染 的本地化字符串。
        /// </summary>
        internal static string render_resolution {
            get {
                return ResourceManager.GetString("render_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重生 的本地化字符串。
        /// </summary>
        internal static string respawn {
            get {
                return ResourceManager.GetString("respawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将你重生，你将对玩家和敌人都是隐形的。 的本地化字符串。
        /// </summary>
        internal static string respawn_descr {
            get {
                return ResourceManager.GetString("respawn_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择语言 的本地化字符串。
        /// </summary>
        internal static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择的玩家 的本地化字符串。
        /// </summary>
        internal static string selected_player {
            get {
                return ResourceManager.GetString("selected_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自身 的本地化字符串。
        /// </summary>
        internal static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送信息 的本地化字符串。
        /// </summary>
        internal static string send_message_misc {
            get {
                return ResourceManager.GetString("send_message_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在聊天中匿名发送信息。 的本地化字符串。
        /// </summary>
        internal static string send_message_misc_descr {
            get {
                return ResourceManager.GetString("send_message_misc_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送信息 的本地化字符串。
        /// </summary>
        internal static string send_message_player {
            get {
                return ResourceManager.GetString("send_message_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在聊天中以选中玩家的身份发送信息。 的本地化字符串。
        /// </summary>
        internal static string send_message_player_descr {
            get {
                return ResourceManager.GetString("send_message_player_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送广播 的本地化字符串。
        /// </summary>
        internal static string send_signal {
            get {
                return ResourceManager.GetString("send_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程发送信号。 的本地化字符串。
        /// </summary>
        internal static string send_signal_descr {
            get {
                return ResourceManager.GetString("send_signal_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敏感的地雷 的本地化字符串。
        /// </summary>
        internal static string sensitive_landmines {
            get {
                return ResourceManager.GetString("sensitive_landmines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当玩家处于杀伤范围内时自动引爆地雷。 的本地化字符串。
        /// </summary>
        internal static string sensitive_landmines_descr {
            get {
                return ResourceManager.GetString("sensitive_landmines_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置指标 的本地化字符串。
        /// </summary>
        internal static string set_quota {
            get {
                return ResourceManager.GetString("set_quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你设置指标。（只有自己是房主时有效） 的本地化字符串。
        /// </summary>
        internal static string set_quota_descr {
            get {
                return ResourceManager.GetString("set_quota_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船 的本地化字符串。
        /// </summary>
        internal static string ship {
            get {
                return ResourceManager.GetString("ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船 的本地化字符串。
        /// </summary>
        internal static string ship_esp {
            get {
                return ResourceManager.GetString("ship_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示飞船。 的本地化字符串。
        /// </summary>
        internal static string ship_esp_descr {
            get {
                return ResourceManager.GetString("ship_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小型战利品。 的本地化字符串。
        /// </summary>
        internal static string small_loot {
            get {
                return ResourceManager.GetString("small_loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷屏信息 的本地化字符串。
        /// </summary>
        internal static string spam_message_misc {
            get {
                return ResourceManager.GetString("spam_message_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在聊天中匿名刷屏信息。 的本地化字符串。
        /// </summary>
        internal static string spam_message_misc_descr {
            get {
                return ResourceManager.GetString("spam_message_misc_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷屏信息。 的本地化字符串。
        /// </summary>
        internal static string spam_message_player {
            get {
                return ResourceManager.GetString("spam_message_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在聊天中以选中玩家的身份刷屏信息。 的本地化字符串。
        /// </summary>
        internal static string spam_message_player_descr {
            get {
                return ResourceManager.GetString("spam_message_player_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成怪物 的本地化字符串。
        /// </summary>
        internal static string spawn_enemy {
            get {
                return ResourceManager.GetString("spawn_enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在选中玩家的位置生成一个随机怪物，需要是房主。 的本地化字符串。
        /// </summary>
        internal static string spawn_enemy_descr {
            get {
                return ResourceManager.GetString("spawn_enemy_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成物品 的本地化字符串。
        /// </summary>
        internal static string spawn_object {
            get {
                return ResourceManager.GetString("spawn_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须是房主才能使用。如果物体名称由多个单词组成，请使用空格，其他单词小写。例如：Apparatus, Key, Red soda 等。 的本地化字符串。
        /// </summary>
        internal static string spawn_object_desc {
            get {
                return ResourceManager.GetString("spawn_object_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动飞船 的本地化字符串。
        /// </summary>
        internal static string start_ship {
            get {
                return ResourceManager.GetString("start_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船将离开当前所在的星球。 的本地化字符串。
        /// </summary>
        internal static string start_ship_descr {
            get {
                return ResourceManager.GetString("start_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蒸汽威胁 的本地化字符串。
        /// </summary>
        internal static string steam_hazard {
            get {
                return ResourceManager.GetString("steam_hazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有的蒸汽区域。 的本地化字符串。
        /// </summary>
        internal static string steam_hazard_esp_descr {
            get {
                return ResourceManager.GetString("steam_hazard_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam 主页 的本地化字符串。
        /// </summary>
        internal static string steam_profile {
            get {
                return ResourceManager.GetString("steam_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开选中玩家的 Steam 主页。 的本地化字符串。
        /// </summary>
        internal static string steam_profile_descr {
            get {
                return ResourceManager.GetString("steam_profile_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蒸汽阀门 的本地化字符串。
        /// </summary>
        internal static string steam_valve {
            get {
                return ResourceManager.GetString("steam_valve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止控制 的本地化字符串。
        /// </summary>
        internal static string stop_possessing {
            get {
                return ResourceManager.GetString("stop_possessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止控制当前的怪物。 的本地化字符串。
        /// </summary>
        internal static string stop_possessing_descr {
            get {
                return ResourceManager.GetString("stop_possessing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紫砂 的本地化字符串。
        /// </summary>
        internal static string suicide {
            get {
                return ResourceManager.GetString("suicide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自杀。 的本地化字符串。
        /// </summary>
        internal static string suicide_descr {
            get {
                return ResourceManager.GetString("suicide_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动表情 的本地化字符串。
        /// </summary>
        internal static string taunt_slide {
            get {
                return ResourceManager.GetString("taunt_slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许你在行走时做表情动作。 的本地化字符串。
        /// </summary>
        internal static string taunt_slide_descr {
            get {
                return ResourceManager.GetString("taunt_slide_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送所有战利品 的本地化字符串。
        /// </summary>
        internal static string teleport_all_items {
            get {
                return ResourceManager.GetString("teleport_all_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将星球上的所有战利品传送给你 的本地化字符串。
        /// </summary>
        internal static string teleport_all_items_descr {
            get {
                return ResourceManager.GetString("teleport_all_items_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送怪物至 的本地化字符串。
        /// </summary>
        internal static string teleport_enemies_to {
            get {
                return ResourceManager.GetString("teleport_enemies_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送所有的怪物到选中玩家处。 的本地化字符串。
        /// </summary>
        internal static string teleport_enemies_to_descr {
            get {
                return ResourceManager.GetString("teleport_enemies_to_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送到飞船 的本地化字符串。
        /// </summary>
        internal static string teleport_player_to_ship {
            get {
                return ResourceManager.GetString("teleport_player_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送选中的玩家到飞船。（需要是房主） 的本地化字符串。
        /// </summary>
        internal static string teleport_player_to_ship_descr {
            get {
                return ResourceManager.GetString("teleport_player_to_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送到 的本地化字符串。
        /// </summary>
        internal static string teleport_to {
            get {
                return ResourceManager.GetString("teleport_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送你到选中玩家的位置 的本地化字符串。
        /// </summary>
        internal static string teleport_to_descr {
            get {
                return ResourceManager.GetString("teleport_to_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送到飞船 的本地化字符串。
        /// </summary>
        internal static string teleport_to_ship {
            get {
                return ResourceManager.GetString("teleport_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送自己到飞船里。 的本地化字符串。
        /// </summary>
        internal static string teleport_to_ship_descr {
            get {
                return ResourceManager.GetString("teleport_to_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端噪音 的本地化字符串。
        /// </summary>
        internal static string terminal_noisemaker {
            get {
                return ResourceManager.GetString("terminal_noisemaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端发出非常恼人的噪音。 的本地化字符串。
        /// </summary>
        internal static string terminal_noisemaker_descr {
            get {
                return ResourceManager.GetString("terminal_noisemaker_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下 INSERT 的本地化字符串。
        /// </summary>
        internal static string tgl_insert {
            get {
                return ResourceManager.GetString("tgl_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第三人称 的本地化字符串。
        /// </summary>
        internal static string thirdperson {
            get {
                return ResourceManager.GetString("thirdperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能提示 的本地化字符串。
        /// </summary>
        internal static string tooltips {
            get {
                return ResourceManager.GetString("tooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示当前光标悬停菜单项的相关信息。 的本地化字符串。
        /// </summary>
        internal static string tooltips_descr {
            get {
                return ResourceManager.GetString("tooltips_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 炮塔 的本地化字符串。
        /// </summary>
        internal static string turret {
            get {
                return ResourceManager.GetString("turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 炮塔绘制距离限制 的本地化字符串。
        /// </summary>
        internal static string turret_distance_limit {
            get {
                return ResourceManager.GetString("turret_distance_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开关以设置炮塔的绘制距离限制。 的本地化字符串。
        /// </summary>
        internal static string turret_distance_limit_descr {
            get {
                return ResourceManager.GetString("turret_distance_limit_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 炮塔 的本地化字符串。
        /// </summary>
        internal static string turret_esp {
            get {
                return ResourceManager.GetString("turret_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有炮塔。 的本地化字符串。
        /// </summary>
        internal static string turret_esp_descr {
            get {
                return ResourceManager.GetString("turret_esp_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经解锁了所有飞船升级。 的本地化字符串。
        /// </summary>
        internal static string u_alrd_unlc_all {
            get {
                return ResourceManager.GetString("u_alrd_unlc_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁所有服装 的本地化字符串。
        /// </summary>
        internal static string unlc_all_suits {
            get {
                return ResourceManager.GetString("unlc_all_suits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁所有服装。 的本地化字符串。
        /// </summary>
        internal static string unlc_all_suits_descr {
            get {
                return ResourceManager.GetString("unlc_all_suits_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁所有升级 的本地化字符串。
        /// </summary>
        internal static string unlc_all_upgrd_ship {
            get {
                return ResourceManager.GetString("unlc_all_upgrd_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁所有飞船升级。 的本地化字符串。
        /// </summary>
        internal static string unlc_all_upgrd_ship_descr {
            get {
                return ResourceManager.GetString("unlc_all_upgrd_ship_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无拾取距离限制 的本地化字符串。
        /// </summary>
        internal static string unlimited_grab_distance {
            get {
                return ResourceManager.GetString("unlimited_grab_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无论距离多远，你都可以与任何物体互动。 的本地化字符串。
        /// </summary>
        internal static string unlimited_grab_distance_descr {
            get {
                return ResourceManager.GetString("unlimited_grab_distance_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁 的本地化字符串。
        /// </summary>
        internal static string unlock {
            get {
                return ResourceManager.GetString("unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁所有的门 的本地化字符串。
        /// </summary>
        internal static string unlock_all_door {
            get {
                return ResourceManager.GetString("unlock_all_door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁所有锁上的门 的本地化字符串。
        /// </summary>
        internal static string unlock_all_door_descr {
            get {
                return ResourceManager.GetString("unlock_all_door_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法选中 的本地化字符串。
        /// </summary>
        internal static string untargetable {
            get {
                return ResourceManager.GetString("untargetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让所有的怪物无视你。 的本地化字符串。
        /// </summary>
        internal static string untargetable_desc {
            get {
                return ResourceManager.GetString("untargetable_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级 的本地化字符串。
        /// </summary>
        internal static string upgrades {
            get {
                return ResourceManager.GetString("upgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阀门 的本地化字符串。
        /// </summary>
        internal static string valve {
            get {
                return ResourceManager.GetString("valve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Apparatus 的本地化字符串。
        /// </summary>
        internal static string watermark {
            get {
                return ResourceManager.GetString("watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 Project Apparatus 的本地化字符串。
        /// </summary>
        internal static string wlc_stp_1 {
            get {
                return ResourceManager.GetString("wlc_stp_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you have suggestions, please create a pull request in the repo or reply to the UC thread. 的本地化字符串。
        /// </summary>
        internal static string wlc_stp_2 {
            get {
                return ResourceManager.GetString("wlc_stp_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you find bugs, please provide some steps on how to reproduce the problem and create an issue or pull request in the repo or reply to the UC thread 的本地化字符串。
        /// </summary>
        internal static string wlc_stp_3 {
            get {
                return ResourceManager.GetString("wlc_stp_3", resourceCulture);
            }
        }
    }
}
